{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7f85d6ad-dab8-485d-9b3c-c6cfddc4a1f3",
   "metadata": {},
   "outputs": [],
   "source": [
    "## 필요 모듈 임포트\n",
    "import pandas as pd\n",
    "from dash import Dash, dcc, html, Input, Output, State\n",
    "import plotly.express as px\n",
    "import pymysql\n",
    "from sqlalchemy import create_engine, text"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5b69524d-df3d-4f58-967d-86a463c17646",
   "metadata": {},
   "outputs": [],
   "source": [
    "## 데이터베이스 연결\n",
    "#접속정보\n",
    "user = \"bigdata\"\n",
    "password = \"Bigdata123!!\"\n",
    "host = \"192.168.56.101\"\n",
    "port = \"3306\"\n",
    "db = \"SampleDB\"\n",
    "\n",
    "#접속 스크립트\n",
    "conn_script = f\"mysql+pymysql://{user}:{password}@{host}:{port}/{db}\"\n",
    "\n",
    "#connection instance\n",
    "engine = create_engine(conn_script)\n",
    "conn = engine.connect()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1e7d83dc-e84b-4c97-8de8-b3b8db0f14e0",
   "metadata": {},
   "outputs": [],
   "source": [
    "qry = \"select year, sum(pop) as pop from world group by year\"\n",
    "df = pd.read_sql(qry,conn)\n",
    "fig = px.line(df, x = \"year\", y = \"pop\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a32d2947-36c7-4ece-aa13-736545eca85b",
   "metadata": {},
   "outputs": [],
   "source": [
    "country = pd.read_sql(\"select distinct country from world\", conn)\n",
    "country = country.loc[:,\"country\"].tolist()\n",
    "country = list(set(country))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e008cdd4-9026-4ac5-b572-ce579bcf2948",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 16:48:28] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 16:48:28] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 16:48:28] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 16:48:28] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 16:48:28] \"GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 16:48:28] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 16:48:28] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 16:48:28] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 16:48:28] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 16:48:28] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 16:48:28] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 16:48:28] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 16:48:28] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 16:48:28] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 16:48:28] \"GET / HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 16:23:28] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 16:23:28] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 16:23:28] \"GET / HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 16:06:17] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 16:06:17] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 16:06:17] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 16:06:17] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 16:06:17] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 16:06:17] \"GET / HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/deps/polyfill@7.v2_1_0m1645078945.12.1.min.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/deps/react@16.v2_1_0m1645078945.14.0.min.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/deps/react-dom@16.v2_1_0m1645078945.14.0.min.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/deps/prop-types@15.v2_1_0m1645078945.7.2.min.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_1_0m1645078945.min.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/dcc/dash_core_components.v2_1_0m1645078945.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/dcc/dash_core_components-shared.v2_1_0m1645078945.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/html/dash_html_components.v2_0_1m1645078945.min.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/dash_table/bundle.v5_1_0m1645078945.js HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/deps/polyfill@7.v2_1_0m1645078945.12.1.min.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/deps/react@16.v2_1_0m1645078945.14.0.min.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/deps/react-dom@16.v2_1_0m1645078945.14.0.min.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/deps/prop-types@15.v2_1_0m1645078945.7.2.min.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_1_0m1645078945.min.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/dcc/dash_core_components.v2_1_0m1645078945.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/dcc/dash_core_components-shared.v2_1_0m1645078945.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/html/dash_html_components.v2_0_1m1645078945.min.js HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/deps/polyfill@7.v2_1_0m1645078945.12.1.min.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/deps/react@16.v2_1_0m1645078945.14.0.min.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/deps/react-dom@16.v2_1_0m1645078945.14.0.min.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/deps/prop-types@15.v2_1_0m1645078945.7.2.min.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_1_0m1645078945.min.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/dcc/dash_core_components.v2_1_0m1645078945.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/dcc/dash_core_components-shared.v2_1_0m1645078945.js HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/deps/polyfill@7.v2_1_0m1645078945.12.1.min.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/deps/react@16.v2_1_0m1645078945.14.0.min.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/deps/react-dom@16.v2_1_0m1645078945.14.0.min.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/deps/prop-types@15.v2_1_0m1645078945.7.2.min.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_1_0m1645078945.min.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/dcc/dash_core_components.v2_1_0m1645078945.js HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/deps/polyfill@7.v2_1_0m1645078945.12.1.min.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/deps/react@16.v2_1_0m1645078945.14.0.min.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/deps/react-dom@16.v2_1_0m1645078945.14.0.min.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/deps/prop-types@15.v2_1_0m1645078945.7.2.min.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_1_0m1645078945.min.js HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/deps/polyfill@7.v2_1_0m1645078945.12.1.min.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/deps/react@16.v2_1_0m1645078945.14.0.min.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/deps/react-dom@16.v2_1_0m1645078945.14.0.min.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/deps/prop-types@15.v2_1_0m1645078945.7.2.min.js HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/deps/polyfill@7.v2_1_0m1645078945.12.1.min.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/deps/react@16.v2_1_0m1645078945.14.0.min.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/deps/react-dom@16.v2_1_0m1645078945.14.0.min.js HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/deps/polyfill@7.v2_1_0m1645078945.12.1.min.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/deps/react@16.v2_1_0m1645078945.14.0.min.js HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET /_dash-component-suites/dash/deps/polyfill@7.v2_1_0m1645078945.12.1.min.js HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 15:55:38] \"GET / HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n"
     ]
    }
   ],
   "source": [
    "## dash application 구성 (front end)\n",
    "app = Dash(__name__)\n",
    "app.layout = html.Div(\n",
    "    [\n",
    "        html.H4(\"연도별 인구수 변화\"),\n",
    "        dcc.RadioItems(id = \"radio-items\",\n",
    "                       options = ['꺾은선그래프','막대그래프','파이그래프'],  # request 부분\n",
    "                      value = '꺾은선그래프',\n",
    "                      inline = True),\n",
    "        dcc.Dropdown(id=\"dropdown-items\",\n",
    "                    options = [{\"label\":i, \"value\":i} for i in country]),\n",
    "        html.Hr(),\n",
    "        dcc.Graph(id=\"plt-graph\")\n",
    "    ]\n",
    "\n",
    ")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f7abc4aa-a839-48d9-b0af-1977d339f573",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "## backend\n",
    "@app.callback(\n",
    "    Output(\"plt-graph\",\"figure\"),\n",
    "    Input(\"radio-items\",\"value\"),\n",
    "    Input(\"dropdown-items\",\"value\")\n",
    ")\n",
    "\n",
    "def update_graph(graph_type,country):\n",
    "    if country == None:\n",
    "        stmt = \"select year, sum(pop) as pop from world group by year\"\n",
    "    else:\n",
    "        stmt = f\"select year, sum(pop) as pop from world where country = '{country}' group by year\"\n",
    "    df = pd.read_sql(stmt, conn)\n",
    "    if graph_type == \"꺾은선그래프\":\n",
    "        fig = px.line(df, x=\"year\", y=\"pop\")\n",
    "    elif graph_type == \"막대그래프\":\n",
    "        fig = px.bar(df, x=\"year\", y=\"pop\")\n",
    "    else:\n",
    "        fig = px.pie(df, values=\"pop\", names=\"year\")\n",
    "    return fig\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c18b8b73-3fb1-43c1-8096-70a724cb3b6a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dash is running on http://192.168.56.101:5555/\n",
      "\n",
      "Dash is running on http://192.168.56.101:5555/\n",
      "\n",
      "Dash is running on http://192.168.56.101:5555/\n",
      "\n",
      "Dash is running on http://192.168.56.101:5555/\n",
      "\n",
      "Dash is running on http://192.168.56.101:5555/\n",
      "\n",
      "Dash is running on http://192.168.56.101:5555/\n",
      "\n",
      "Dash is running on http://192.168.56.101:5555/\n",
      "\n",
      "Dash is running on http://192.168.56.101:5555/\n",
      "\n",
      "Dash is running on http://192.168.56.101:5555/\n",
      "\n",
      "Dash is running on http://192.168.56.101:5555/\n",
      "\n",
      "Dash is running on http://192.168.56.101:5555/\n",
      "\n",
      "Dash is running on http://192.168.56.101:5555/\n",
      "\n",
      "Dash is running on http://192.168.56.101:5555/\n",
      "\n",
      "Dash is running on http://192.168.56.101:5555/\n",
      "\n",
      "Dash is running on http://192.168.56.101:5555/\n",
      "\n",
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
      "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:27] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:29] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:31] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:33] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:34] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:35] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:27] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:29] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:31] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:33] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:34] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:27] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:29] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:31] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:33] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:27] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:29] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:31] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:27] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:29] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:27] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:27] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:27] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:27] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:27] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:27] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:27] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:28] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:34:27] \"GET / HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:31:26] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:31:27] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:31:27] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:31:27] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:31:26] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:31:27] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:31:27] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:31:26] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:31:27] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:31:26] \"GET / HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:26:20] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:26:20] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:26:20] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:26:20] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:26:20] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:26:20] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:26:20] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:26:20] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:26:20] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:26:20] \"GET / HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:18:55] \"GET / HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:17:58] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:17:58] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:17:58] \"GET / HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:11:44] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:11:44] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:11:44] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:11:44] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:11:44] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:11:44] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:11:44] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:11:44] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:11:44] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:11:44] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:11:44] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:11:44] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:11:44] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:11:44] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:11:44] \"GET / HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:55] \"GET / HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:14] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:15] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:15] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:15] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:15] \"GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:14] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:15] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:15] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:15] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:14] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:15] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:15] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:14] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:15] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:10:14] \"GET / HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:03:19] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:03:19] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:03:19] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:03:19] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:03:19] \"GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:03:19] \"GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:03:19] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:03:19] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:03:19] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:03:19] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:03:19] \"GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:03:19] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:03:19] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:03:19] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:03:19] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:03:19] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:03:19] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:03:19] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:03:19] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:03:19] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:03:19] \"GET / HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:02:29] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:02:29] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:02:29] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:02:29] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:02:29] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:02:29] \"GET / HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "192.168.56.1 - - [18/Feb/2022 17:00:05] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:00:05] \"POST /_dash-update-component HTTP/1.1192.168.56.1 - - [18/Feb/2022 17:00:05] \""
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/ejchoi/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_4285/657946945.py\", line 14, in update_graph\n",
      "    fig = px.pie(df, x=\"year\", y=\"pop\")\n",
      "TypeError: pie() got an unexpected keyword argument 'x'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:00:03] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:00:03] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:00:03] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:00:03] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:00:03] \"GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:00:03] \"GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:00:03] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:00:03] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:00:03] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:00:03] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:00:03] \"GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:00:03] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:00:03] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:00:03] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:00:03] \"GET /_favicon.ico?v=2.1.0 HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:00:03] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:00:03] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:00:03] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:00:03] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 17:00:03] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 17:00:03] \"GET / HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 16:57:58] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 16:57:58] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 16:57:58] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 16:57:58] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [18/Feb/2022 16:57:58] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [18/Feb/2022 16:57:58] \"GET / HTTP/1.1\" 200 -\n",
      " * Running on http://192.168.56.101:5555/ (Press CTRL+C to quit)\n"
     ]
    }
   ],
   "source": [
    "## 서버 구동\n",
    "app.run_server(host=host,port=5555)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "32a67127-46e6-4ad5-8ed4-c513da4d52ae",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
